name: EntityInfo
main: ltguide.entityinfo.EntityInfo
version: 0.2
author: ltguide
description: Entity Info
commands:
  entityinfo:
    description: Entity Info
    aliases: [einfo,ei]
    usage: '/<command> <@ | Entity ID | # | Entity Type>'
permissions:
    entityinfo.*:
        description: 
        children:
             entityinfo.use: true
             entityinfo.reload: false
    entityinfo.use:
        description: Allows you to use the command
        default: op
    entityinfo.reload:
        description: Allows you to reload the config file
        default: op